replicaCount: 1

image:
  repository: "registry-quay-quay-operator.apps.acm-dcl.clarocl.com/acm/hello-world-ui-flask"
  tag: "1.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: hello-world-ui-flask.apps.acm-dcl.clarocl.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  name: default # Cambia esto si usas un ServiceAccount personalizado

role:
  name: cluster-admin # Cambia esto al nombre del Role que desees asociar

resources: {}
nodeSelector: {}
tolerations: []
affinity: []

env:
  REGISTRY_URL: "registry-quay-quay-operator.apps.acm-dcl.clarocl.com/myproject"
  CLUSTER_NAME: "demo-cluster"
